---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runnerset-voxpupuli-k8s-pod-template
data:
  pod-template.yaml: |
    spec:
      containers:
        - name: $job
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "16"
              memory: "32Gi"
